### ISSUE TITLE
node-sass error

### ISSUE THREAD

**Issue by ojasp** [owtf/owtf-docker#36]
I installed the docker image on Kali Linux, however when I run the image, I get no UI, and the dev tools shows the following error:
```
Error: Module build failed: ModuleBuildError: Module build failed: Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (79)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.2
    at module.exports (/owtf/owtf/webui/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/owtf/owtf/webui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/owtf/owtf/webui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadLoader (/owtf/owtf/webui/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/owtf/owtf/webui/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/owtf/owtf/webui/node_modules/webpack/lib/NormalModule.js:181:3)
    at NormalModule.build (/owtf/owtf/webui/node_modules/webpack/lib/NormalModule.js:274:15)
    at Compilation.buildModule (/owtf/owtf/webui/node_modules/webpack/lib/Compilation.js:149:10)
    at /owtf/owtf/webui/node_modules/webpack/lib/Compilation.js:447:10
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModuleFactory.js:241:5
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModuleFactory.js:94:13
    at /owtf/owtf/webui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.<anonymous> (/owtf/owtf/webui/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModule.js:194:19
    at /owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:170:18
    at loadLoader (/owtf/owtf/webui/node_modules/loader-runner/lib/loadLoader.js:27:11)
    at iteratePitchingLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/owtf/owtf/webui/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/owtf/owtf/webui/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/owtf/owtf/webui/node_modules/webpack/lib/NormalModule.js:181:3)
    at NormalModule.build (/owtf/owtf/webui/node_modules/webpack/lib/NormalModule.js:274:15)
    at Compilation.buildModule (/owtf/owtf/webui/node_modules/webpack/lib/Compilation.js:149:10)
    at /owtf/owtf/webui/node_modules/webpack/lib/Compilation.js:447:10
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModuleFactory.js:241:5
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModuleFactory.js:94:13
    at /owtf/owtf/webui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.<anonymous> (/owtf/owtf/webui/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/owtf/owtf/webui/node_modules/webpack/node_modules/tapable/lib/Tapable.js:272:13)
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModuleFactory.js:69:10
    at /owtf/owtf/webui/node_modules/webpack/lib/NormalModuleFactory.js:194:7
    at processTicksAndRejections (internal/process/task_queues.js:79:11) bundle.js:26:19395
```
Here's what the page looks like:
![image](https://user-images.githubusercontent.com/15022394/71481739-b01d3980-27c4-11ea-883b-9320292af8bb.png)

I have ran recommended steps that I found on stackoverflow and other github repos to fix this node-sass error but none of them have helped. I have tried:
$ npm update node-sass
$ npm rebuild node-sass
$ npm uninstall node-sass -g && node cache clean && node install node-sass

Thank you!

**Comment by mwager** [comment]
Same problem. Installed via:

```
git clone https://github.com/owtf/owtf
cd owtf
make compose
```
